[package]
name = "reticulum-rust-esp32"
version = "0.1.0"
edition = "2024"

[dependencies]
esp-hal = { version = "~1.0", features = ["esp32", "unstable", "defmt"] }
esp-bootloader-esp-idf = { version = "0.4.0", features = ["esp32"] }
esp-backtrace = { version = "0.18.1", features = [
    "esp32",
    "panic-handler",
	"defmt",
] }
esp-println = { version = "0.16.1", features = ["esp32", "log-04", "defmt-espflash"] }
defmt = "1.0.1"
critical-section = "1.2"
esp-wifi-hal = { git = "https://github.com/esp32-open-mac/esp-wifi-hal", features = ["esp32", "defmt"] }
static_cell = "2.1.1"

[features]
esp32 = [
    "esp-hal/esp32",
]
# Flash as sender (device A: transmits HELLO, waits for echo)
sender = []
# Flash as receiver (device B: receives any frame and echoes it back)
receiver = []

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"
